### ISSUE TITLE
Touch Not Working On Apple iOS Device

### ISSUE THREAD

**Issue by jmscreation** [CodeSmith32/nimblejs#1]
Touches do not work on the Apple iOS platform.
Known browser's that do not function:
- Chrome iOS
- Safari iOS

**Comment by CodeSmith32** [comment]
After reviewing the code you sent privately, it appears on Apple iOS devices that the browser event touch `identifier` property is set to a number from `-2147483648` to `2147483647` whereas on typical androids and desktops supporting touch, the touch is a number starting at `0`.

I noted your code, however, tried to use `touch.fingers[0]` (`touch` being an instance of `nimble.Touch`). Since `nimble.Touch::fingers` is an object mapping the `identifier` to the finger object, you can't use `touch.fingers[0]` since the identifier isn't always 0 (as is the case on iOS). Instead, to get the first touch, you could do something like,

```
var id;
for(id in touch.fingers) break;

// code making use of ... touch.fingers[id] ...
```
